//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BEUEjercicio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carrera
    {
        public int idcarrera { get; set; }
        public string nombre { get; set; }
        public string departamento { get; set; }
        public string modalidad { get; set; }
        public Nullable<int> duracion { get; set; }
        public string coordinador { get; set; }
        public string titulo_otorgado { get; set; }
    }
}
